# Generated by GPT for professional data backfill

from django.conf import settings
from django.db import migrations


def backfill_movie_user(apps, schema_editor):
    Movie = apps.get_model("api", "Movie")
    UserModel = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    # If there are no existing rows, nothing to do.
    if not Movie.objects.filter(user__isnull=True).exists():
        return

    # Create (or reuse) a deterministic "system" user for legacy rows.
    legacy_username = "legacy"
    legacy_email = "legacy@example.com"
    legacy_user, _ = UserModel.objects.get_or_create(
        username=legacy_username,
        defaults={"email": legacy_email},
    )

    Movie.objects.filter(user__isnull=True).update(user=legacy_user)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_movie_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_movie_user, migrations.RunPython.noop),
    ]

