# Generated by Django 6.0.3 on 2026-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pickedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedmovie',
            name='choice',
            field=models.CharField(choices=[('saved', 'Saved'), ('pass', 'Pass')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
