# Generated by Django 6.0.3 on 2026-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pickedmovie_choice_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedmovie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
