# Generated by Django 6.0.3 on 2026-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pickedmovie_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedmovie',
            name='choice',
            field=models.CharField(choices=[('saved', 'Saved'), ('liked', 'Liked'), ('pass', 'Pass')], max_length=10),
        ),
    ]
